version: '3.8'

services:
  app:
    build:
      context: ../../
      dockerfile: Dockerfile
    container_name: xpense-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/xpense_tracker
      SPRING_DATASOURCE_USERNAME: xpense_admin
      SPRING_DATASOURCE_PASSWORD: xpenseTracker1234
    depends_on:
      - db

  db:
    image: postgres
    container_name: xpense-db
    environment:
      POSTGRES_USER: xpense_admin
      POSTGRES_PASSWORD: xpenseTracker1234
      POSTGRES_DB: xpense_tracker
    ports:
      - "5432:5432"
    volumes:
      - xpense_tracker_data_v2:/var/lib/postgresql/data

volumes:
  xpense_tracker_data_v2:
    name: xpense_tracker_data_v2