volumes:
  xpense_tracker_data_v2:
    name: xpense_tracker_data_v2

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: xpense_admin
      POSTGRES_PASSWORD: xpenseTracker1234
      POSTGRES_DB: xpense_tracker
    ports:
      - "5432:5432"
    volumes:
      - xpense_tracker_data_v2:/var/lib/postgresql/data
